<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)-v1.0.1
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR ZAN GROUP, ANY PROBLEM PLS CONTACT Zan Group<zan@zanphp.io>
 * @generated
 */

namespace Com\Miaoju\Device\Entity;

use Kdt\Iron\Nova\Foundation\Protocol\TStruct;
use Thrift\Type\TType;


class DeviceStruct extends TStruct {
  /**
   * @var int
   */
  public $id = null;
  /**
   * @var string
   */
  public $device = null;
  /**
   * @var string
   */
  public $device_name = null;
  /**
   * @var string
   */
  public $province = null;
  /**
   * @var string
   */
  public $city = null;
  /**
   * @var string
   */
  public $area = null;
  /**
   * @var string
   */
  public $address = null;
  /**
   * @var int
   */
  public $state = null;
  /**
   * @var int
   */
  public $create_time = null;

  protected $structSpec = [
    1 => [
      'var' => 'id',
      'type' => TType::I32,
      ],
    2 => [
      'var' => 'device',
      'type' => TType::STRING,
      ],
    3 => [
      'var' => 'device_name',
      'type' => TType::STRING,
      ],
    4 => [
      'var' => 'province',
      'type' => TType::STRING,
      ],
    5 => [
      'var' => 'city',
      'type' => TType::STRING,
      ],
    6 => [
      'var' => 'area',
      'type' => TType::STRING,
      ],
    7 => [
      'var' => 'address',
      'type' => TType::STRING,
      ],
    8 => [
      'var' => 'state',
      'type' => TType::I32,
      ],
    9 => [
      'var' => 'create_time',
      'type' => TType::I32,
      ],
    ];

}

