<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)-v1.0.1
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR ZAN GROUP, ANY PROBLEM PLS CONTACT Zan Group<zan@zanphp.io>
 * @generated
 */

namespace Com\Miaoju\Device\Interfaces;

interface DeviceService {
  /**
   * @throws \Com\Miaoju\Device\Exception\DeviceServiceException
   */
  public function throwException();
  /**
   * @param \Com\Miaoju\Device\Entity\DeviceStruct $device_struct
   * @return array
   */
  public function getdeviceid(\Com\Miaoju\Device\Entity\DeviceStruct $device_struct);
  /**
   * @param \Com\Miaoju\Device\Entity\DeviceStruct $device_struct
   * @return array
   */
  public function createdevice(\Com\Miaoju\Device\Entity\DeviceStruct $device_struct);
  /**
   * @param \Com\Miaoju\Device\Entity\DeviceStruct $device_struct
   * @return array
   */
  public function updatedevice(\Com\Miaoju\Device\Entity\DeviceStruct $device_struct);
}

