<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)-v1.0.1
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR ZAN GROUP, ANY PROBLEM PLS CONTACT Zan Group<zan@zanphp.io>
 * @generated
 */

namespace Com\Miaoju\Device\Servicespecification;

use Kdt\Iron\Nova\Foundation\TSpecification;
use Thrift\Type\TType;


class DeviceService extends TSpecification {

  protected $serviceName = 'Com.Miaoju.Device.Service.DeviceService';

  protected $inputStructSpec = [
    'throwException' => [
    ],
    'getdeviceid' => [
      1 => [
        'var' => 'device_struct',
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Entity\DeviceStruct',
        ],
    ],
    'createdevice' => [
      1 => [
        'var' => 'device_struct',
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Entity\DeviceStruct',
        ],
    ],
    'updatedevice' => [
      1 => [
        'var' => 'device_struct',
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Entity\DeviceStruct',
        ],
    ],
  ];
  protected $outputStructSpec = [

    'throwException' => [
      'type' => TType::VOID,
    ],
    'getdeviceid' => [
      'type' => TType::MAP,
      'ktype' => TType::STRING,
      'vtype' => TType::STRUCT,
      'key' => [
        'type' => TType::STRING,
      ],
      'val' => [
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Entity\BaseStruct',
        ],
    ],
    'createdevice' => [
      'type' => TType::MAP,
      'ktype' => TType::STRING,
      'vtype' => TType::STRUCT,
      'key' => [
        'type' => TType::STRING,
      ],
      'val' => [
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Entity\BaseStruct',
        ],
    ],
    'updatedevice' => [
      'type' => TType::MAP,
      'ktype' => TType::STRING,
      'vtype' => TType::STRUCT,
      'key' => [
        'type' => TType::STRING,
      ],
      'val' => [
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Entity\BaseStruct',
        ],
    ],
  ];
  protected $exceptionStructSpec = [

    'throwException' => [
      1 => [
        'var' => 'e',
        'type' => TType::STRUCT,
        'class' => '\Com\Miaoju\Device\Exception\DeviceServiceException',
        ],
    ],
  ];
}

